function [fitresult, gof] = createFit(f, ff)
%CREATEFIT(F,FF)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : f
%      Y Output: ff
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 29-Jan-2020 10:21:42


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( f, ff );

% Set up fittype and options.
ft = 'pchipinterp';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

%Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'ff vs. f', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
% xlabel( 'f', 'Interpreter', 'none' );
% ylabel( 'ff', 'Interpreter', 'none' );
% grid on


